services:
  gin:
    build:
      context: .
      dockerfile: ./docker/gin/Dockerfile
    volumes:
      - "./api:/go/src"
    extra_hosts:
      - "host.docker.internal:host-gateway"
    init: true
    command: ["sh", "start.sh"]

  react:
    build:
      context: .
      dockerfile: docker/react/Dockerfile
    volumes:
      - ./:/usr/src/app
      - /usr/src/app/api
      - ./node_modules:/usr/src/app/node_modules
    init: true
    command: ["sh", "start.sh"]

  nginx:
    image: nginx:latest
    volumes:
      - "./docker/nginx/nginx.conf:/etc/nginx/conf.d/default.conf"
    ports:
      - 80:80
